[package]
name = "tokio-loop"
version = "0.1.0"
authors = ["Craig Barber <craigb@mojotech.com>"]
edition = "2018"

[dependencies]
futures = "0.3.0"
tokio = { version = "0.2.11", features = ["full"] }
